language: php
php:
    - '5.6'
    - '7.1'
    - hhvm
    - nightly
before_script:
    - composer self-update
    - composer install

script: ./vendor/bin/phpunit --bootstrap src/autoload.php tests/Container/IocContainerTest.php 
